### PR TITLE
Build for aarch64

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@scopatz, this is ready for review :)

**Comment by scopatz** [comment]
This should probably go through the usual arch migration. Please add `attr` to this file: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt

**Comment by saraedum** [comment]
Thanks. I wasn't aware of that.

**Pull request closed without merging**
